### ISSUE TITLE
Allow moving of CollectionsJournal

### ISSUE THREAD

**Issue by syndenbock** [nezroy/DeModal#12]
I saw someone on reddit asked for this and you replied that this frame requires BetterWardrobe to be installed for it to be moveable.
I have a pretty similar personal addon and running this code when Blizzard_Collections is loaded makes the CollectionsJournal moveable without any errors, maybe that works for you too (My addon doesn't use the Default UI positions handling and stores and restores the positions itself).

```
    local checkBox = _G.WardrobeTransmogFrame.ToggleSecondaryAppearanceCheckbox;
    local label = checkBox.Label;

    label:ClearAllPoints();
    label:SetPoint('LEFT', checkBox, 'RIGHT', 2, 1);
    label:SetPoint('RIGHT', checkBox, 'RIGHT', 160, 1);
```

**Comment by nezroy** [comment]
Thanks, it is definitely the anchor loop from that checkbox that causes issues. Fixed it a few days ago #1 :)
