### ISSUE TITLE
Certain windows appear unmovable

### ISSUE THREAD

**Issue by sebid** [nezroy/DeModal#14]
I have noticed that certain windows appear unmovable. I am unsure if some might be protected.
- ArchaeologyFrame
- GuideFrame - Mentor / Guide Signup
- AlliedRacesFrame - Allied Races Embassy
- ChromieTimeFrame
- ItemInteractionFrame - Runeforge Reclaim / Creation Catalyst
- TorghastLevelPickerFrame
- BlackMarketFrame - BMAH
- AzeriteRespecFrame - Azerite Reforge
- AzeriteEmpoweredItemUI
- CovenantPreviewFrame
- ChallengesKeystoneFrame
... and probably some other I did not check.

GarrisonMonumentFrame - Probably minor, for when you select a statue in garrison.

Not implemented/Protected:
- StoreFrame - WoW Shop
- PlayerChoiceFrame - Command Board / Vindicaar / Garrison Assault

**Comment by sebid** [comment]
Would it be preferable for me to go through /fstack and let you know which frame is which rather than this?

**Comment by lenoirrichelieu** [comment]
Also Guidl&Communities frame seems unmovable. Also, after open it you cannot close with from X but with ESC. And if you reopen it's bugged and shows nothing

**Comment by nezroy** [comment]
CovenantPreviewFrame doesn't liike being moved, so that one's out.

ChallengesKeystoneFrame I'm going to leave alone for now. Even if it works, I don't want to risk blowing up people's keystones in some weird way.

The remaining have been made movable.
