### ISSUE TITLE
11.0.2 Lua Error

### ISSUE THREAD

**Issue by carlos5152** [nezroy/DeModal#37]
Hi 
Demodal not working for me and I'm getting the following error :

18x DeModal/core/SettingsMixin.lua:37: attempt to index field 'CheckBox' (a nil value)
[string "@DeModal/core/SettingsMixin.lua"]:37: in function `AddOptions'
[string "@DeModal/core/SettingsMixin.lua"]:107: in function `Init'
[string "@DeModal/DeModal.lua"]:22: in main chunk

Locals:
self = Frame {
 ScrollBar = Frame {
 }
 Header = Frame {
 }
 ScrollBox = Frame {
 }
}
f = Frame {
 PerCharOption = Frame {
 }
 callbackTables = <table> {
 }
 Event = <table> {
 }
}
btn = Frame {
 Checkbox = CheckButton {
 }
 Text = FontString {
 }
 cbrHandles = <table> {
 }
 Tooltip = Frame {
 }
 NewFeature = Frame {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Save windows only for this character"
(*temporary) = "TOPLEFT"
(*temporary) = 0
(*temporary) = -10
(*temporary) = Frame {
 HoverBackground = Texture {
 }
 tooltipAnchoring = "ANCHOR_RIGHT"
 tooltipYOffset = 0
 tooltipXOffset = -10
}
(*temporary) = "attempt to index field 'CheckBox' (a nil value)"

**Comment by nezroy** [comment]
This got fixed two releases ago, are you sure you are using the latest version?

**Comment by carlos5152** [comment]
Oh sorry for some reason curseforge was not detecting it so it was not updated I installed it again and now the issue is fixed.
Thanks
